#!/usr/bin/env bash

declare -A SAVED_DIRS=(
  [" TypeScript"]="/mnt/e/Learning/Typescript/"
  [" TypeORM"]="/mnt/e/Notes/TypeORM"
  [" FFMPEG"]="/mnt/e/Notes/FFMPEG"
  [" HTTP"]="/mnt/e/Notes/XMLHttpRequest"
  ["󱜥 Scripts"]="/usr/sbin"
  ["󰍛 Graphite"]="/mnt/e/Graphite"
)
howto() {
  clear

  selected_dir=$(printf "%s\n" "${!SAVED_DIRS[@]}" |
    fzf --border=rounded \
      --border-label="📁 Select Project" \
      --border-label-pos=3 \
      --margin=30% \
      --padding=1 \
      --layout=reverse \
      --height=80% \
      --min-height=5 \
      --color='border:#c1ebf5')

  if [ -z "$selected_dir" ]; then
    echo "No directory selected."
    return
  fi

  DIR="${SAVED_DIRS[$selected_dir]}"
  cd "$DIR" || return
  echo "Changed directory to: $DIR"
  exec bash # Start a new shell session in the selected directory
}

add_dir() {
  echo "Enter directory name (no spaces):"
  read -r dirname
  echo "Enter directory path:"
  read -r dirpath
  echo "SAVED_DIRS[\"$dirname\"]=\"$dirpath\"" >>~/.config/howto/dirs.sh
  source ~/.config/howto/dirs.sh
}

init_config() {
  mkdir -p ~/.config/howto
  if [ ! -f ~/.config/howto/dirs.sh ]; then
    echo "#!/bin/bash" >~/.config/howto/dirs.sh
    echo "declare -A SAVED_DIRS" >>~/.config/howto/dirs.sh
    echo "SAVED_DIRS[\"typescript\"]=\"/mnt/e/Learning/Typescript/\"" >>~/.config/howto/dirs.sh
  fi
  source ~/.config/howto/dirs.sh
}

init_config

case "$1" in
"add")
  add_dir
  ;;
*)
  howto
  ;;
esac

